global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-apps'
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ['producer:8000', 'consumer:8000']
